Web_11/Controllers/AdminController.cs
using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Web_11.Models;
using Web_11.Models.data;

namespace Web_11.Controllers
{
    public class AdminController : Controller
    {
        private readonly FootballNewsContext _context;

        public AdminController(FootballNewsContext context)
        {
            _context = context;
        }
        public IActionResult TinTuc()
        {
            TinTucModel tinTuc = new TinTucModel
            {
                Tintucs = _context.Tintuc.ToArray()
            };
            return View(tinTuc);
        }
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tintuc = await _context.Tintuc
                .FirstOrDefaultAsync(m => m.IdTinTuc == id);
            if (tintuc == null)
            {
                return NotFound();
            }

            return View(tintuc);
        }

        // GET: Tintucs/Create
        public IActionResult CreateTinTuc()
        {
            return View();
        }
        public IActionResult CreateNoiDung()
        {
            return View();
        }
        public IActionResult CreateHinhAnh()
        {
            return View();
        }
        public IActionResult CreateSubTinTuc()
        {
            return View();
        }
        public IActionResult CreateHashTag()
        {
            return View();
        }

        // POST: Tintucs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateTinTuc([Bind("IdTinTuc,TieuDe,Avatar,TomTat,LuotTuongTac,LuotXem,TrangThaiHienThi,")] Tintuc  tintuc)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tintuc);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tintuc);
        }
        public IActionResult CreateTinTucTemp([Bind("IdTinTuc,TieuDe,Avatar,TomTat,LuotTuongTac,LuotXem,TrangThaiHienThi")] TinTucTemp tintuc)
        {
            
            return View(tintuc);
        }
       
        // GET: Tintucs/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tintuc = await _context.Tintuc.FindAsync(id);
            if (tintuc == null)
            {
                return NotFound();
            }
            return View(tintuc);
        }

        // POST: Tintucs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("IdTinTuc,TieuDe,Avatar,TomTat,LuotTuongTac,LuotXem,TrangThaiHienThi")] Tintuc tintuc)
        {
            if (id != tintuc.IdTinTuc)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tintuc);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TintucExists(tintuc.IdTinTuc))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tintuc);
        }

        // GET: Tintucs/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tintuc = await _context.Tintuc
                .FirstOrDefaultAsync(m => m.IdTinTuc == id);
            if (tintuc == null)
            {
                return NotFound();
            }

            return View(tintuc);
        }

        // POST: Tintucs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var tintuc = await _context.Tintuc.FindAsync(id);
            _context.Tintuc.Remove(tintuc);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TintucExists(string id)
        {
            return _context.Tintuc.Any(e => e.IdTinTuc == id);
        }


    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Web_11/Controllers/ThongTinXepHangsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Web_11.Models;
using Web_11.Models.data;

namespace Web_11.Controllers
{
    public class ThongTinXepHangsController : Controller
    {
        public (string IDDoiBong, int? SoTran, int? Thang, int? Hoa, int? Thua, string HieuSo, int? Diem)[] listbangxephang { get; set; }
        int?[] listDiem = new int?[100];
        public (string DoiBong, int? Diem)[] DiemXepHang { get; set; }
        public IList<ThongTinXepHang> thongTinXepHangs { get; set; }
        private readonly FootballNewsContext _context;

        public ThongTinXepHangsController(FootballNewsContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            BangXepHangViewModel bangXepHangViewModel = new BangXepHangViewModel();
            bangXepHangViewModel.listbangxephang = GetBangXepHang();
            bangXepHangViewModel.DiemXepHang = GetDiem();
            return View(bangXepHangViewModel);
        }

        public (string IDDoiBong, int? SoTran, int? Thang, int? Hoa, int? Thua, string HieuSo, int? Diem)[] GetBangXepHang()
        {
            List<ThongTinXepHang> tempBXH = _context.ThongTinXepHang.ToList();
            int temp = 0;
            listbangxephang = new (string IDDoiBong, int? SoTran, int? Thang, int? Hoa, int? Thua, string HieuSo, int? Diem)[100];
            foreach (var item in tempBXH)
            {
                listbangxephang[temp] = (GetTenDoiBong(item.IdDoiBong), item.SoTran, item.Thang, item.Hoa, item.Thua, item.HieuSo, item.Diem);
                temp++;
            }
            return listbangxephang;
        }
        public string GetTenDoiBong(string id)
        {
            string temp = "";
            foreach (var item in _context.Doibong)
            {
                if (item.IdDoiBong == id)
                {
                    temp = item.TenDoi;
                }

            }
            return temp;
        }

        public (string DoiBong, int? Diem)[] GetDiem()
        {
            int temp = 0;
            DiemXepHang = new (string DoiBong, int? Diem)[100];
            thongTinXepHangs = _context.ThongTinXepHang.ToArray();
            foreach (var item in _context.ThongTinXepHang)
            {
                listDiem[temp] = item.Diem;
                temp++;
            }
            temp = 0;
            foreach (var item in thongTinXepHangs)
            {
                if (item.Diem == listDiem[temp])
                {
                    DiemXepHang[temp] = (item.IdDoiBong, item.Diem = (item.Thang * 3) + item.Hoa);
                    temp++;
                }
            }
            return DiemXepHang;
        }

    }
}

Web_11/Controllers/TicketsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Web_11.Models;
using Web_11.Models.data;

namespace Web_11.Controllers
{
    public class TicketsController : Controller
    {
        public List<Doibong> doibongs { get; set; }
        public (string IDve, string srcLogoDoiNha, string srcLogoDoiKhach, DateTime? Thoigian)[] ListVeVsLogo { get; set; }
        public (string IDve, string srcLogoDoiNha, string srcLogoDoiKhach, DateTime? Thoigian) VeDuocChon { get; set; }
        private readonly FootballNewsContext _context;

        public TicketsController(FootballNewsContext context)
        {
            _context = context;
        }

        // GET: Tickets
        public IActionResult Index()
        {
            TicketsViewsModel ticketsViewsModel = new TicketsViewsModel();
            ticketsViewsModel.hinhanhQcs = _context.HinhanhQc.ToList();
            ticketsViewsModel.tickets = _context.Ticket.ToList();
            ticketsViewsModel.trandaus = _context.Trandau.ToList();
            ticketsViewsModel.doibongs = _context.Doibong.ToList();
            ticketsViewsModel.ListVeVsLogo = GetListVe();
            return View(ticketsViewsModel);
        }
        // GET: Tickets/Details/5
        public (string IDve, string srcLogoDoiNha, string srcLogoDoiKhach, DateTime? Thoigian)[] GetListVe()
        {
            List<Ticket> tempTicket = _context.Ticket.ToList();
            int temp = 0;
            ListVeVsLogo = new (string IDve, string srcLogoDoiNha, string srcLogoDoiKhach, DateTime? Thoigian)[100];
            foreach (var item in tempTicket)
            {
                ListVeVsLogo[temp] = (item.IdVe, GetLogoSrc(item.DoiNha), GetLogoSrc(item.DoiKhach), item.ThoiGianBatDau);
                temp++;
            }
            return ListVeVsLogo;
        }
        public string GetLogoSrc(string id)
        {
            string temp = "";
            foreach (var item in _context.Doibong)
            {
                if (item.IdDoiBong == id)
                {
                    temp = item.SourceLogo;
                }

            }
            return temp;
        }
        public (string IDve, string srcLogoDoiNha, string srcLogoDoiKhach, DateTime? Thoigian) GetTicket(string id, (string IDve, string srcLogoDoiNha, string srcLogoDoiKhach, DateTime? Thoigian)[] listve)
        {
            foreach (var item in listve)
            {
                if (item.IDve==id)
                {
                     return item;
                }
            }
            return ("", "", "", null);
        }
       
            public IActionResult Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            TicketsViewsModel ticketsViewsModel = new TicketsViewsModel();
            ticketsViewsModel.tickets = _context.Ticket.ToList();
            ticketsViewsModel.trandaus = _context.Trandau.ToList();
            ticketsViewsModel.doibongs = _context.Doibong.ToList();
            ticketsViewsModel.ListVeVsLogo = GetListVe();
            ticketsViewsModel.VeDuocChon = GetTicket(id,ListVeVsLogo);

            return View(ticketsViewsModel);
        }

    }
}

Web_11/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web_11</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-inverter bg-white border-bottom box-shadow mb-3 sticky-top">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Admin</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark active" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TinTuc" asp-action="Index">Tin Tức</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ThongTinXepHangs" asp-action="index">Bảng Xếp Hạng</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="LichThiDau">Lịch Thi Đấu</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tickets" asp-action="Index">Mua Vé</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Thongtincobans" asp-action="Index">Thông Tin Đội Bóng</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="page-footer font-small teal pt-4">

        <!-- Footer Text -->
        <div class="container-fluid text-center text-md-left">

            <!-- Grid row -->
            <div class="row">

                <!-- Grid column -->
                <div class="col-md-6 mt-md-0 mt-3">

                    <div class="row">
                        <!-- Content -->
                        <div class="col-md-6 mt-md-6 mt-3">

                            <div class="row">
                                <h5 class="text-uppercase mt-3 font-weight-bold">Tin Tức Thể Thao</h5>
                            </div>

                        </div>
                        <div class="col-md-6 mt-md-6    mt-3">

                            <div class="row">
                                <a class="navbar-brand" href="#">
                                    <img src="https://secureservercdn.net/166.62.108.43/bns.d72.myftpupload.com/wp-content/uploads/2018/12/BongdaEx_2.png" class="img-fluid" alt="Responsive image" height="50" width="100">
                                </a>
                            </div>

                        </div>
                        <p>Tòa soạn: 59c Nguyễn Đình Chiểu, Q.3 ,TP.Hồ Chí Minh</p>
                        <p> Cơ sở chủ quản: Hội xuất bản Việt Nam</p>

                    </div>


                </div>
                <!-- Grid column -->

                <hr class="clearfix w-100 d-md-none pb-3">

                <!-- Grid column -->
                <div class="col-md-6 mb-md-0 mb-3 mt-5 ">

                    <!-- Content -->
                    <p>HotLine: 0523364071</p>
                    <p>Liên Hệ Quảng Cáo: 0979528720</p>
                    <p>Liên Kết Qua Các Ứng Dụng:</p>
                    <a class="fb-ic" style="color: white;font-size: larger;">
                        <i class="fab fa-facebook-f fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
                    </a>
                    <a class="ins-ic" style="color: white;font-size: larger;">
                        <i class="fab fa-instagram fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
                    </a>

                </div>
                <!-- Grid column -->

            </div>
            <!-- Grid row -->

        </div>
        <!-- Footer Text -->
        <!-- Copyright -->
        <div class="footer-copyright text-center py-3">
            © 2020 Copyright:
            <a href="#" style="color: white;">QuanLiBongDa.com</a>
        </div>
        <!-- Copyright -->

    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Web_11/Views/Shared/_Layout_Admin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web_11</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Admin</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark active" asp-area="" asp-controller="Admin" asp-action="Index">Tổng Quan</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark active" asp-area="" asp-controller="Admin" asp-action="TinTuc">Tin Tức</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="TinTuc">Vé Bán</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="BXH">Doanh Thu</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="LichThiDau">Giải Đấu</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <address>Tòa soạn: 59c Nguyễn Đình Chiểu, Q.3 ,TP.Hồ Chí Minh</address>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>